### ISSUE TITLE
Handling of concurrent games?

### ISSUE THREAD

**Issue by marcroberts** [sbehrends/Live-WorldCup-Notification-for-Slack#1]
The last games in the group stages are played concurrently, at first glance this looks like it will only handle 1 'live' game at a time.

Otherwise, great work. Thanks!

**Comment by j0k3r** [comment]
Good point :+1:

**Comment by sbehrends** [comment]
Good point.
In the object of mathces there will be two items with b_Live = true then.
The best option would be to have an array of "live games" and continuously add/remove live games.

**Comment by sbehrends** [comment]
Solved by @Cyborg572
