### ISSUE TITLE
Getting an { [Error: socket hang up] code: 'ECONNRESET' } error

### ISSUE THREAD

**Issue by nhuber** [sbehrends/Live-WorldCup-Notification-for-Slack#12]
running it locally

**Comment by nhuber** [comment]
cc @sbehrends!!!

Is the FIFA API getting hammered or something?

**Comment by nhuber** [comment]
Ok nm, it looks like this is just occasional b/c we're refreshing the connection every 5 seconds. Great job guys!

**Comment by sbehrends** [comment]
We have no control over FIFA API :/
