### ISSUE TITLE
2018 World Cup

### ISSUE THREAD

**Issue by sbehrends** [sbehrends/Live-WorldCup-Notification-for-Slack#20]
Migrate API calls for Russia 2018 World Cup

**Comment by simonhrogers** [comment]
@sbehrends Did you get anywhere with this? About to look into it for our work!

**Comment by sbehrends** [comment]
Hey, @simonhrogers. Yes! I have two alternatives. One is standalone, right now available in [20-wc-2018](https://github.com/sbehrends/Live-WorldCup-Notification-for-Slack/tree/20-wc-2018) branch. And then there is a Slack app that you can easily install [here](https://worldcup.now.sh)

**Comment by simonhrogers** [comment]
Amazing! Thanks so much, we're enjoying now :)
