### ISSUE TITLE
check out my twitter-hipchat version

### ISSUE THREAD

**Issue by jefforulez** [sbehrends/Live-WorldCup-Notification-for-Slack#5]
this is comment, not an issue...     

very nice job!    

checkout my twitter-hipchat version at http://github.com/jefforulez/gooolbot

i wonder which approach gets updates faster?   pull from fifa api or stream from twitter api....

**Comment by sbehrends** [comment]
I chosed FIFA API because it's official and used in their main App (iOS & Android). I'm sure it has less than 30 seconds delay.
