### ISSUE TITLE
Very strange problem. Score ranging.

### ISSUE THREAD

**Issue by RobertoSchneiders** [sbehrends/Live-WorldCup-Notification-for-Slack#6]
```
WorldCupBot [7:03 PM] 
Começa Chile vs Austrália
Chile 0:0 Austrália

WorldCupBot [7:11 PM] 
Chile 1:0 Austrália
Chile 2:0 Austrália

WorldCupBot [7:35 PM]
Chile 2:0 Austrália
Chile 2:1 Austrália
Chile 2:0 Austrália
Chile 2:1 Austrália
Chile 2:0 Austrália
Chile 2:1 Austrália
Chile 2:0 Austrália
Chile 2:1 Austrália
```

```
WorldCupBot [1:31 PM] 
Alemanha 2:0 Portugal
WorldCupBot [1:32 PM] 
Alemanha 1:0 Portugal
Alemanha 2:0 Portugal
WorldCupBot [1:33 PM] 
Alemanha 1:0 Portugal
Alemanha 2:0 Portugal
```

**Comment by RobertoSchneiders** [comment]
Maybe we have to increase the refresh time?

**Comment by RobertoSchneiders** [comment]
I have the bot running on two servers. sometimes this bug occurs on both, sometimes not.

**Comment by sbehrends** [comment]
It just happened again. The solution could be to have a variable for each team score and only notify if scoreHome > n_HomeGoals.

```
Alemania 2:0 Portugal
Alemania 3:0 Portugal
Alemania 2:0 Portugal
Alemania 3:0 Portugal
```

**Comment by RobertoSchneiders** [comment]
I made some changes. I will test tomorrow. If run as espected, I'll send a pullrequest.

**Comment by sbehrends** [comment]
Ok. Let me know. Otherwise I was about to code a solution that could also handle more than one game at once an display Goal information

**Comment by RobertoSchneiders** [comment]
What I did is just a workaround to try to solve this specific problem. 

I think it's a good idea to implement the way you said, go ahead.

**Comment by sbehrends** [comment]
I thought we can use http://live.mobileapp.fifa.com/api/wc/match/300186456/es (Match ID) data.actions to show the information.

**Comment by RobertoSchneiders** [comment]
My code did not work. :/
