### ISSUE TITLE
Wrong scores for Argentina vs Bosnia-Herzegovina

### ISSUE THREAD

**Issue by RobertoSchneiders** [sbehrends/Live-WorldCup-Notification-for-Slack#7]
```
WorldCupBot [7:01 PM] 
Começa Argentina vs Bósnia e Herzegovina
Argentina 0:0 Bósnia e Herzegovina
Argentina 1:0 Bósnia e Herzegovina

WorldCupBot [8:22 PM] 
Argentina 2:0 Bósnia e Herzegovina
```

That game ended 2:1

Occurred similarly in two instances of the bot.

**Comment by sbehrends** [comment]
I saw it too. It was a mistake from FIFA API. I was watching the game with the FIFA iOS App open and it didn't show either.

Wasn't a code mistake from the bot.js, was a FIFA guys mistake.

**Comment by RobertoSchneiders** [comment]
I suspected that too. But as I saw so later, was not sure. 

Thank you.
